### ISSUE TITLE
Video addition to list Normalizing Flows: An Introduction and Review of Current Methods

### ISSUE THREAD

**Issue by Chris-On-PC** [janosh/awesome-normalizing-flows#11]
Great overview!
Thanks for the effort

Is there a spot for the [video tutorial](https://www.youtube.com/watch?v=u3vVyFVU_lI&list=PLg5qedO6csRg7e4Q9qYvtBDcvb4B2Jjxg&index=22&t=1s) created by one of the autohers of [Normalizing Flows: An Introduction and Review of Current Methods](https://arxiv.org/abs/1908.09257v4) and presented at ECCV2020?

**Comment by janosh** [comment]
Definitely. Please submit a PR adding it to the [Videos section](https://github.com/janosh/awesome-normalizing-flows#-videos).

**Comment by Chris-On-PC** [comment]
Ah I see it's already been added since I last checked it. Great you're keeping the repo active!

**Comment by janosh** [comment]
@Chris-On-PC That was @ksachdeva in #15 actually. 👍
