### ISSUE TITLE
Add SurVAE Flows

### ISSUE THREAD

**Issue by hushon** [janosh/awesome-normalizing-flows#12]
Hi, thanks for the comprehensive list and nice summary of materials. I would like to recommend [SurVAE Flows](https://arxiv.org/abs/2007.02731) to the list which I had an interesting read.

They present a generalized framework (SurVAE Flows) which encompasses Flows (deterministic maps) and VAEs (stochastic maps). By seeing a deterministic map (x=f(z)) as a limiting case of a stochastic map (x~p(x|z)), the ELBO can be reinterpreted as a change of variables formula for the stochastic maps. Moreover, stochastic maps are able to model surjections, which might be useful in incorporating bottleneck architectures to Flows. They also give few examples of surjective layers, which can be composed together with Flow layers.

**Comment by janosh** [comment]
Oh yeah, I meant to add this paper but then forgot about it. Thanks for the reminder. Would you like to submit a PR?
