### ISSUE TITLE
I write on normalizing flows on my website and am wondering if it is fitted for this repo

### ISSUE THREAD

**Issue by A-Vzer** [janosh/awesome-normalizing-flows#17]
You can check it at https://amaanv.com/articles under the headin 'Normalizing Flows'. I do it as a hobby and intend to write more. If you think it adds value to the repo I would love it if you can add it.

**Comment by A-Vzer** [comment]
I also have a paper at : https://arxiv.org/abs/2103.12672 but it is not published.

**Comment by janosh** [comment]
@A-Vzer Thanks for reaching out. If you combined your posts into a single article, that would make them more suitable for this repo as I only link to single posts, not whole blogs.

Regarding your paper, I'm afraid this repo is meant for peer-reviewed research only.

**Comment by A-Vzer** [comment]
@janosh Thanks for replying. Loud and clear, if I ever combine the posts I'll make a PR to this repo. Have a nice day.
