### ISSUE TITLE
NF resource recommendation

### ISSUE THREAD

**Issue by iphysresearch** [janosh/awesome-normalizing-flows#18]
**Variational Inference using Normalizing Flows (VINF)**

PDF: https://pierresegonne.github.io/VINF/
Medium: https://medium.com/swlh/normalizing-flows-are-not-magic-22752d0c924
GitHub: https://github.com/pierresegonne/VINF

**Comment by janosh** [comment]
Feel free to add this under a new subsection of the `## Code` section titled `### TFP Repos`.

**Comment by iphysresearch** [comment]
> Feel free to add this under a new subsection of the `## Code` section titled `### TFP Repos`.

OK👌
