### ISSUE TITLE
[WIP] Add stochastic NFs paper

### ISSUE THREAD

**Issue by jejjohnson** [janosh/awesome-normalizing-flows#3]
Add stochastic normalizing flows paper. Adds stochasticity to your NF to help do better sampling.

* https://arxiv.org/abs/2002.06707

**Comment by janosh** [comment]
Funnily enough there's a naming clash. 5 days later, [people at Berkeley coined the same term for a different technique](https://arxiv.org/abs/2002.09547). We should include both with brief descriptions to highlight their differences.

**Comment by janosh** [comment]
Here's another one to include in the next PR: https://arxiv.org/abs/2006.02425
