### ISSUE TITLE
Unlisted JAX package and paper

### ISSUE THREAD

**Issue by Qazalbash** [janosh/awesome-normalizing-flows#65]
- [flowMC](https://github.com/kazewong/flowMC): Normalizing-flow enhanced sampling package for probabilistic inference
- [Efficient Bayesian Sampling Using Normalizing Flows to Assist Markov Chain Monte Carlo Methods](https://openreview.net/pdf?id=mvtooHbjOwx)
- [Adaptive Monte Carlo augmented with normalizing flows](https://www.pnas.org/doi/10.1073/pnas.2109420119)

**Comment by janosh** [comment]
those look great, was also going to add this one https://arxiv.org/abs/2406.14426. would you like to make a PR?

**Comment by Qazalbash** [comment]
Yeah sure, do you want me to add the one you have mentioned?

**Comment by janosh** [comment]
yes please, that would be much appreciated!
