### ISSUE TITLE
Multiple `authors` need multiple `authors_urls`

### ISSUE THREAD

**Issue by Qazalbash** [janosh/awesome-normalizing-flows#69]
I see you have set the field `authors` to be `str` it would make more sense for it to be a `list[str]`. Same for `authors_url`.

**Comment by janosh** [comment]
would accept a PR to change `authors` to `list[dict['name' | 'url' | ..., str]]`

**Comment by DanielYang59** [comment]
@Qazalbash Would you be interested in opening a PR to implement this? Or I could help implement this if you're not interested :)

**Comment by Qazalbash** [comment]
@DanielYang59 yes please you can work on it :)

**Comment by DanielYang59** [comment]
Okay! Thanks for the confirm
