### ISSUE TITLE
Video tutorial - Normalizing Flows - Motivations, The Big Idea, & Essential Foundations

### ISSUE THREAD

**Issue by ksachdeva** [janosh/awesome-normalizing-flows#9]
https://www.youtube.com/watch?v=IuXU2dBOJyw

Hi @janosh,

I just uploaded a comprehensive tutorial on YouTube.

Since it is my video, I am not sending the pull request and request you to assess if it is good enough to be part of this repository. 

Regards & thanks
Kapil

**Comment by janosh** [comment]
Hi Kapil, that's great work and a very nice introduction to flows. It definitely belongs in this repo. Please submit for a PR for it.

**Comment by ksachdeva** [comment]
Thanks @janosh for the kind words.
